Rails:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'db/**/*.rb'
    - 'spec/**/*.rb'
    - 'lib/tasks/**/*.rake'

Metrics/MethodLength:
  CountComments: false
  Max: 20
  Exclude:
    - 'db/migrate/**/*.rb'

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'spec/**/*.rb'
