AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  ExtraDetails: true
  TargetRubyVersion: 2.5

  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Rails:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'db/**/*.rb'
    - 'spec/**/*.rb'
    - 'lib/tasks/**/*.rake'

Metrics/LineLength:
  Max: 120
  IgnoredPatterns:
    - '^# [^\n]+'

Metrics/MethodLength:
  CountComments: false
  Max: 20
  Exclude:
    - 'db/migrate/**/*.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'config/deploy/**/*.rb'
    - 'db/seeds/**/*.rb'
    - 'spec/**/*.rb'
