app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
    - redis
postgres:
  image: postgres:10.3
  ports:
    - "5432"
redis:
  image: redis:4.0.9
  ports:
    - "6379"
