version: 2
jobs:
  build:
    working_directory: ~/cohdb
    docker: &docker
      - image: cohdb/circleci:latest
        environment:
          VAULT_PATH: /lib/vault/target/release/libvault.so
          PGHOST: 127.0.0.1
          PGUSER: cohdb
          RAILS_ENV: test
      - image: circleci/postgres:10.3-alpine
        environment:
          POSTGRES_USER: cohdb
          POSTGRES_DB: cohdb_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - restore_cache:
          keys:
            - cohdb-bundle-{{ checksum "Gemfile.lock" }}
            - cohdb-bundle-

      - run:
          name: Bundle Install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - save_cache:
          key: cohdb-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - persist_to_workspace:
          root: .
          paths:
             - vendor/bundle
  rubocop:
    working_directory: ~/cohdb
    docker: *docker
    steps:
      - checkout

      - attach_workspace:
          at: ~/cohdb

      - restore_cache:
          keys:
            - cohdb-bundle-{{ checksum "Gemfile.lock" }}
            - cohdb-bundle-

      - run:
          name: Bundle Install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - run:
          name: Rubocop
          command: bundle exec rubocop

  rspecs:
    working_directory: ~/cohdb
    docker: *docker
    steps:
      - checkout

      - attach_workspace:
          at: ~/cohdb

      - restore_cache:
          keys:
            - cohdb-bundle-{{ checksum "Gemfile.lock" }}
            - cohdb-bundle-

      - run:
          name: Bundle Install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:create db:migrate --trace

      - run:
          name: Tests
          command: bundle exec rspec spec

workflows:
  version: 2
  run_tests:
    jobs:
      - build

      - rubocop:
          requires:
            - build

      - rspecs:
          requires:
            - build
